name: Run tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - '3.8'
    runs-on: ${{ matrix.os }}
    name: Run pytest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
