name: Verify grjobs setup.py

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - '3.8'
          
    runs-on: ${{ matrix.os }}
    name: Check the installation builds
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install
        run: |
          pip install --user wheel
          pip install --user https://github.com/nestauk/grjobs/archive/${GITHUB_REF##*/}.zip
          
      - name: Check that installation has worked
        run: |
          python -c "import grjobs"
          python -c "from grjobs.pipeline.green_classifier import load_model"
